# Generated by Django 5.1 on 2024-08-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('desription', models.CharField(max_length=255)),
                ('discount', models.FloatField()),
            ],
        ),
    ]
